-- AlterTable
ALTER TABLE "attendances" ADD COLUMN     "overtimeMinutes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "overtimeRate" DOUBLE PRECISION NOT NULL DEFAULT 1.15;

-- AlterTable
ALTER TABLE "payrolls" ADD COLUMN     "cnpsEmployee" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "cnpsEmployer" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "fdfpTax" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "grossSalary" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "housingAllowance" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "igrTax" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "itsTax" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "overtimePay" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "sursalaire" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalDeductions" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "transportAllowance" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "housingAllowance" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "partsIGR" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
ADD COLUMN     "sursalaire" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "transportAllowance" DOUBLE PRECISION NOT NULL DEFAULT 0;
