import { z } from "zod";

export const createEmployeeSchema = z.object({
  name: z.string().min(2, "Le nom doit comporter au moins 2 caractères"),
  email: z.string().email("Adresse email invalide"),
  role: z.enum(["admin", "manager", "employee", "accountant"]).optional(),
  departmentId: z.string().optional(),
  shiftId: z.string().optional(),
  employeeId: z.string().optional(),
  salary: z.number().min(0).optional(),
  sursalaire: z.number().min(0).optional(),
  transportAllowance: z.number().min(0).optional(),
  housingAllowance: z.number().min(0).optional(),
  partsIGR: z.number().min(1).max(5).optional(),
  cnpsNumber: z.string().optional(),
  idCardNumber: z.string().optional(),
  bankAccount: z.string().optional(),
  bankName: z.string().optional(),
  paymentMethod: z.string().optional(),
  joiningDate: z.string().optional(),
  civility: z.string().optional(),
  gender: z.string().optional(),
  birthDate: z.string().optional(),
  birthPlace: z.string().optional(),
  idCardType: z.string().optional(),
  nationality: z.string().optional(),
  maritalStatus: z.string().optional(),
  childrenCount: z.number().optional(),
  address: z.string().optional(),
  phone: z.string().optional(),
  contractType: z.string().optional(),
  contractSignDate: z.string().optional(),
  cddDurationMonths: z.string().optional(),
  exitDate: z.string().optional(),
  direction: z.string().optional(),
  service: z.string().optional(),
  jobTitle: z.string().optional(),
  jobCode: z.string().optional(),
  regime: z.string().optional(),
  paymentType: z.string().optional(),
  category: z.string().optional(),
  cnpsExempt: z.boolean().optional(),
  department: z.string().optional(),
}).passthrough();

export const updateEmployeeSchema = createEmployeeSchema.partial();

export const listEmployeesQuerySchema = z.object({
  departmentId: z.string().optional(),
  isActive: z.enum(["true", "false"]).optional(),
  search: z.string().optional(),
});
